version: '3.3'

services:
  mysql_testDB:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_USER: testDB
      MYSQL_PASSWORD: testDB
      MYSQL_ROOT_PASSWORD: testDB
    ports:
      - "3306:3306"